n1=int(input("Enter a number 1: "))
n2=int(input("Enter a number 2: "))
n3=int(input("Enter a number 3: "))
n4=int(input("Enter a number 4: "))
n5=int(input("Enter a number 5: "))
n6=int(input("Enter a number 6: "))
n7=int(input("Enter a number 7: "))
n8=int(input("Enter a number 8: "))
s=set([n1,n2,n3,n4,n5,n6,n7,n8])
print(s,type(s))
