s={}
name=input("Enter your name: ")
lang=input("Enter your favorite language: ")
s.update({name:lang})
name=input("Enter your name: ")
lang=input("Enter your favorite language: ")
s.update({name:lang})
name=input("Enter your name: ")
lang=input("Enter your favorite language: ")
s.update({name:lang})
name=input("Enter your name: ")
lang=input("Enter your favorite language: ")
s.update({name:lang})
print(s)